# `holesailCpp` is threaded in by flake.nix: a NixOS module cannot reach a
# flake input on its own, and the C++ port is one. It stays optional so this
# file still works when imported by path — only `implementation = "cpp"` needs
# it, and that path explains itself rather than failing obscurely.
{ holesailCpp ? null }:
{
  config,
  lib,
  pkgs,
  ...
}:
with lib;
let
  holesail = (import ../holesail.nix {inherit pkgs;});
  cppPackage =
    if holesailCpp != null then holesailCpp
    else throw ''
      services.holesail-server: implementation = "cpp" needs the holesail-cpp
      package, which this module only receives when it is taken from the
      holesail-nix flake, e.g.

        imports = [ inputs.holesail.nixosModules.<system>.holesail-server ];

      Importing modules/holesail-server.nix by path gives you the JS package
      only. Set `package` explicitly if you need the C++ port that way.
    '';
  cfg = config.services.holesail-server;
in
{
  options.services.holesail-server = mkOption {
    # A function, so `package` can default off `implementation` in the same
    # submodule.
    type = types.attrsOf (types.submodule ({ config, ... }: {
      options = {
        enable = mkEnableOption "Enable this Holesail server instance.";
        
        user = mkOption {
          description = "User account under which holesail runs.";
          default = "holesail";
          type = types.str;
        };
        group = mkOption {
          description = "Group under which holesail runs.";
          default = "holesail";
          type = types.str;
        };
        implementation = mkOption {
          type = types.enum [ "js" "cpp" ];
          default = "js";
          example = "cpp";
          description = ''
            Which holesail to run.

            `js` is the upstream Node implementation (the default, and what the
            Holesail project supports). `cpp` is holesail-cpp, an independent
            C++ port that speaks the same protocol — same connection strings,
            same key derivation, same DHT records — in roughly 3 MB of RSS
            instead of ~78 MB, with no Node runtime on the target. Worth it on
            constrained hardware; otherwise prefer `js`.

            This only picks the default for `package`; setting `package`
            directly still wins.
          '';
        };
        package = mkOption {
          type = types.package;
          default = if config.implementation == "cpp" then cppPackage else holesail;
          defaultText = literalExpression
            "the package matching `implementation` (JS holesail, or holesail-cpp)";
          description = ''
            The holesail package to run. Normally left alone — set
            `implementation` instead. Override this to pin a specific build;
            both CLIs take the same flags.
          '';
        };
        host = mkOption {
          type = types.str;
          default = "127.0.0.1";
          description = "Host address to use for this Holesail server instance.";
        };
        port = mkOption {
          type = types.port;
          description = "The local port to expose over Holesail. This option is required.";
        };
        udp = mkOption {
          type = types.bool;
          default = false;
          description = "Enable UDP instead of TCP.";
        };
        key = mkOption {
          type = types.str;
          default = "";
          description = "The connection string of the Holesail server. In private mode it should start with 'hs://s000' If empty, a random one will be generated by holesail.";
        };
        key-file = mkOption {
          type = types.str;
          default = "";
          description = "The path to a file containing the connection string of the Holesail server. If null, the key option will be used.";
        };
        public = mkOption {
          type = types.bool;
          default = false;
          description = "Whether to announce the server to the DHT. If you want to use public mode with a fixed connection key, you should
                        use as key just a random string of exactly 32 characters";
        };
        log = mkOption {
          type = types.bool;
          default = false;
          description = "Whether to enable logs of holesail.";
        };
        key-output-file = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Path to save the generated hs:// connection key. Useful for automation and capturing connection strings.";
        };
      };
    }));
    description = "Configure multiple Holesail server instances.";
    default = {};
  };

  config = mkIf (any (name: cfg.${name}.enable) (attrNames cfg)) {
    systemd.services = genAttrs (attrNames cfg) (name: 
      let
        instanceCfg = cfg.${name};
      in
        mkIf instanceCfg.enable {
          description = "Holesail server (${name})";
          wantedBy = [ "multi-user.target" ];
          after = [ "network.target" ];
          path = [ instanceCfg.package ];
          script = let
            args = lib.concatStringsSep " " (lib.filter (x: x != "") [
              (if instanceCfg.key != "" then "--key ${instanceCfg.key}" else "")
              (if instanceCfg.key-file != "" then "--key $(cat ${instanceCfg.key-file})" else "")
              "--live ${toString instanceCfg.port}"
              "--host ${instanceCfg.host}"
              (if instanceCfg.udp then "--udp" else "")
              (if instanceCfg.public then "--public" else "")
              (if instanceCfg.log then "--log" else "")
            ]);
          in ''
            holesail ${args}
          '';
          serviceConfig = {
            Type = "simple";
            Restart = "always";
            RestartSec = "10";
            User = instanceCfg.user;
            Group = instanceCfg.group;
          } // lib.optionalAttrs (instanceCfg.key-output-file != null) {
            ExecStartPost = "${pkgs.bash}/bin/bash -c 'sleep 4; ${pkgs.systemd}/bin/journalctl -u ${name}.service --since \"5 seconds ago\" --no-pager | grep -oE \"hs://[a-zA-Z0-9]+\" | head -1 > ${instanceCfg.key-output-file}'";
          };
        }
    );

    users.users = lib.mkIf (any (name: cfg.${name}.user == "holesail") (attrNames cfg)) {
      holesail = {
        isSystemUser = true;
        group = "holesail";
        home = "/var/lib/holesail";
      };
    };

    users.groups = lib.mkIf (any (name: cfg.${name}.group == "holesail") (attrNames cfg)) {
      holesail = { };
    };
  };

  meta.maintainers = with maintainers; [ jjacke13 ];
}
